questions = [
    "What is the capital of France?",
    "Which planet is known as the Red Planet?",
    "What is 5 + 7?",
    "Which animal is known as man's best friend?",
    "What color do you get when you mix red and white?",
    "How many days are in a week?",
    "What is the largest ocean on Earth?",
    "Which fruit is yellow and curved?",
    "What is the freezing point of water (°C)?",
    "Which shape has three sides?",
    "What is the opposite of 'hot'?",
    "Which month comes after June?",
    "What do bees make?",
    "What is 10 divided by 2?",
    "Which is a primary color?",
    "Which animal says 'meow'?",
    "How many legs does a spider have?",
    "What is the first letter of the alphabet?",
    "Which season comes after winter?",
    "What is the color of grass?"
]

choices = [
    ["Berlin", "Madrid", "Paris", "Rome"],
    ["Earth", "Mars", "Jupiter", "Venus"],
    ["10", "11", "12", "13"],
    ["Cat", "Dog", "Horse", "Dolphin"],
    ["Pink", "Purple", "Orange", "Brown"],
    ["5", "6", "7", "8"],
    ["Atlantic", "Indian", "Pacific", "Arctic"],
    ["Apple", "Banana", "Grape", "Cherry"],
    ["0", "10", "32", "-5"],
    ["Square", "Triangle", "Circle", "Rectangle"],
    ["Warm", "Cold", "Cool", "Boiling"],
    ["May", "July", "August", "April"],
    ["Milk", "Honey", "Bread", "Wax"],
    ["2", "3", "5", "8"],
    ["Green", "Purple", "Blue", "Pink"],
    ["Dog", "Cat", "Cow", "Bird"],
    ["6", "8", "10", "4"],
    ["A", "B", "C", "D"],
    ["Fall", "Spring", "Summer", "Autumn"],
    ["Blue", "Green", "Yellow", "Red"]
]